### ISSUE TITLE
how the hell did i commit when i only starred?

### ISSUE THREAD

**Issue by PoIygon** [Explosion-Scratch/real-kwellercat-is-epic#7]
confusion

**Comment by kbtganesh** [comment]
@PoIygon - And now you are a contributor

**Comment by PoIygon** [comment]
> @PoIygon - And now you are a contributor

???

**Comment by Explosion-Scratch** [comment]
This repo uses this GitHub action:
https://github.com/Explosion-Scratch/Nagol12344-is-a-unicorn/blob/5cc26e6235f5ea1e2a0769f575af84eecffbfabb/.github/workflows/rename.yml#L30-L35

By default is uses `${{ github.actor }}` as the author. Which in the case of this repo is whoever starred.
